# Generated by Django 3.2 on 2021-06-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publishing_date', 'id']},
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Technology', 'Teknoloji'), ('Sport', 'Spor'), ('Science', 'Bilim'), ('Cinema , Series', 'Sinema , Dizi'), ('Game', 'Oyun'), ('Software', 'Yazilim')], default='Yazilim', max_length=15),
        ),
    ]
