# Generated by Django 3.2 on 2021-06-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0002_auto_20210614_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='post',
            name='read',
            field=models.IntegerField(default=0, verbose_name='Populer Ekleme Sira'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Technology', 'Teknoloji'), ('Sport', 'Spor'), ('Science', 'Bilim'), ('Cinema , Series', 'Sinema , Dizi'), ('Game', 'Oyun'), ('Software', 'Yazilim')], default='Yazilim', max_length=15, verbose_name='Kategori'),
        ),
    ]
